# Generated by Django 4.2.19 on 2025-03-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(
                blank=True,
                default='profile_pics/default.jpg',
                upload_to='profile_pics/'),
        ),
    ]
