# Generated by Django 4.2.19 on 2025-03-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Beginner',
                     'Beginner'),
                    ('Intermediate',
                     'Intermediate'),
                    ('Advanced',
                     'Advanced')],
                max_length=20,
                null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_hikes',
            field=models.TextField(
                blank=True,
                null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_handle',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True),
        ),
    ]
