# Generated by Django 4.2.19 on 2025-03-07 19:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_experience_level_profile_favorite_hikes_and_more'), ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default='profile_pics/default.jpg',
                max_length=255,
                verbose_name='image'),
        ),
    ]
