# Generated by Django 4.2.19 on 2025-03-07 19:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/YOUR_CLOUD_NAME/image/upload/v1234567890/profile_pics/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
