# Generated by Django 4.2.19 on 2025-02-24 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_post_options_post_slug_post_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('content',
                 models.TextField()),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('approved',
                 models.BooleanField(
                     default=False)),
                ('author',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='comments',
                     to=settings.AUTH_USER_MODEL)),
                ('post',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='comments',
                     to='blog.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
