# Generated by Django 4.2.19 on 2025-02-25 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='comment_upvotes',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='post_upvotes',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
